name: Build spacebar Nginx proxy docker image

on:
  push:
    branches: ["master"]
    paths:
      - "spacebar-server/**"
  pull_request:
    branches: ["master"]
    paths:
      - "spacebar-server/**"
  workflow_dispatch:
    inputs:
      push:
        description: "Push to Docker Hub"
        required: true
        default: false
        type: boolean
jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_SPACEBAR_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SPACEBAR_TOKEN }}
      - name: Build and push with PostgresSQL AMD64
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:spacebar-server-client-proxy/"
          platforms: linux/amd64
          file: Dockerfile-nginx
          push: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.push) }}
          tags: niggggggo/spacebarchat-nginx:latest
          provenance: false
      - name: Create and push manifest images
        uses: Noelware/docker-manifest-action@master
        with:
          inputs: niggggggo/spacebarchat-nginx:latest
          images: niggggggo/spacebarchat-nginx:latest
          push: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.push) }}
          amend: true
     